### ISSUE TITLE
Test IBS ISO's using openQA

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1003]
There is already an existing openQA test for Elemental ISOs, this issue is about figuring out what is actually missing to start using the test in IBS builds (ideally in the context of CR:ToTest subrproject builds)

**Comment by ldevulder** [comment]
Is it still necessary? As we don't directly provide ISO anymore, no?

**Comment by kkaempf** [comment]
Well, `.iso` files are still created as a build artifact.
They still need to be tested (openQA being sufficient 🤔 ) before we wrap them into a container image for distribution 😉

**Comment by ldevulder** [comment]
Merge/Pull Requests opened:
- Test code: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/19286 ✅
- Trigger scripts: https://gitlab.suse.de/openqa/openqa-trigger-from-ibs-plugin/-/merge_requests/172 ✅
- Salt States (deployment): https://gitlab.suse.de/openqa/salt-states-openqa/-/merge_requests/1167 ✅ 
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1663 ✅
- Jobs group definition (backup): https://github.com/rancher/elemental/pull/1397 ✅
- openqa WebUI configuration ✅
- use the correct path to ber sure that we are testing the ISO generated with `docker` instead of `podman` ✅

**Comment by ldevulder** [comment]
All is done and the tests are working, closing.
