### ISSUE TITLE
Upgrade to latest Dev OS image is broken

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#1417]
CI is [failing](https://github.com/rancher/elemental/actions/runs/9075878612/job/24940576342) on upgrade test. I did a manual test to verify and yes upgrade is broken. The OS upgrade is done and after the reboot the OS is stuck on this:
![Screenshot from 2024-05-14 12-53-03](https://github.com/rancher/elemental/assets/25102165/51d95da9-36af-423c-b39e-56ac26efd9af)

**Comment by davidcassany** [comment]
This seams to be caused by the relabeling step at boot. Relabelling the persistent partition can take quite a while on a provisioned system. I can't see how we can prevent this when upgrading from an old image to a SELinux ready image...

Probably we should not support upgrading from a non SELinux system (or SELinux on permessive mode) to a system with SELinux in enforce mode unless explicitly stated.

**Comment by davidcassany** [comment]
reopening, closed by mistake

**Comment by davidcassany** [comment]
Moving to needs review as we need to check if after merging rancher/elemental-toolkit#2081 and rancher/elemental-toolkit#2080 this turns back to an acceptable behavior (not getting stuck for so long at boot relabeling).
I'd say if upgrade does not get stuck at firstboot for more than 10min we are good.

In any case we have to consider this will be a problem for any upgrade having a huge persistent partition... probably we should not relabel by default when moving from a system without SELinux to one with SELinux.

**Comment by ldevulder** [comment]
No issue since the merge of the PR: https://github.com/rancher/elemental/actions/runs/9169123202. Closing.
