### ISSUE TITLE
SELinux/podman: `elemental install` fails on rsync on `baremetal` iso

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#1449]
openQA and manual tests shown that the `elemental install` command fails on rsync. Some logs are available [here](https://openqa.suse.de/tests/14518486/logfile?filename=serial_terminal.txt).

**Comment by kkaempf** [comment]
Hmm, `parted` isn't happy either

~~~
DEBU[2024-06-04T15:41:36Z] Running cmd: 'parted --script --machine -- /dev/vda unit s mklabel gpt' 
DEBU[2024-06-04T15:41:36Z] Running cmd: 'partx -u /dev/vda'             
DEBU[2024-06-04T15:41:36Z] 'partx' command reported an error: exit status 1 
DEBU[2024-06-04T15:41:36Z] 'partx' command output: partx: specified range <1:0> does not make sense 
~~~

Otherwise it seems to be SELinux again 😞 

~~~
         32.77K   0%    0.00kB/s    0:00:00  rsync: [receiver] rsync_xal_set: lremovexattr("/run/elemental/state/.snapshots/1/snapshot.workDir/.","security.selinux") failed: Permission denied (13)
~~~

And `elemental-register` is failing (to be expected without a management cluster around).

Everything else looks fine.

**Comment by davidcassany** [comment]
This is strange, I can't reproduce it in Staging. However the error actually looks familiar, seams to be a SELinux issue with rsync trying to copy the extended attributes from one location to another one.

In Dev, within the SELinux spike this got fixed here in this refactor https://github.com/rancher/elemental-toolkit/commit/4d469e7f3a04ba79bdb992e828db4df72c13ea1f. However I can't explain why this is not a problem in Staging. I tried diffing packages between the two images and the only difference I found was on the build count of elemental packages, all other were the same.

**Comment by davidcassany** [comment]
I think I found the issue, the failing image was build with podman, while the non failing images were build with containerd and docker. I bet the difference is caused by different extended attributes at build time depending on the container runtime backend, later this turns to be a problem when running an rsync call that is not filtering out selinux attributes.

Need to verify it, but I think that `Dev` images including https://github.com/rancher/elemental-toolkit/commit/4d469e7f3a04ba79bdb992e828db4df72c13ea1f should NOT have this issue even if podman is used to build them.

IMHO all this goes down to the issue of building a filesystem inside a container with a SELinux enabled host and then keeping SELinux attributes in the built filesystem. This is specially sensitive for disk and ISO images.

**Comment by kkaempf** [comment]
Considered fixed as of last comment.
