### ISSUE TITLE
`elemental-rt` iso is using the wrong initrd

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#1450]
Simply try to boot the iso (for example `sl-micro-6.0-rt.x86_64-2.1.1-Build3.33.iso`) and it fails. You can find more information [here](https://openqa.suse.de/tests/14518488#step/installation/4).

**Comment by kkaempf** [comment]
This one seems related to iscsi 🤔

**Comment by davidcassany** [comment]
Found the bug, not related to `iscsi`. The problem is that this image is based on baremetal one, hence it already included an elemental generated initrd for the baremetal image. Initrds are named with `elemental.initrd-<kernel-version>`, the problem is that `zypper in -kernel-default kernel-rt` does not remove any previous initrd and the kernel version is different, hence in `/boot` folder we have two different initrds: `/boot/elemental.initrd-6.4.0-17-default` and `/boot/elemental.initrd-6.4.0-8-rt`. The ISO and grub setup just uses first match of `/boot/elemental.initrd-*`, hence we were using the wrong initrd 🤦🏽 
I am preparing a fix in elemental-toolkit to actually remove any already pre-existing elemental initrd when recreating a new one.
