### ISSUE TITLE
build-iso still pulls from quay.io

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#263]
`elemental build-iso` should run offline when the base image is available in the local image cache.
Currently it still pulls data from quay.io (grub2 files apparently).

Not sure why this happens. Either `elemental` looks at the wrong places in the image (or not at all :wink:)

Everything needed for ISO building should be provided by [node-image](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Teal52/node-image) and [builder-image](https://build.opensuse.org/package/show/isv:Rancher:Elemental:Teal52/builder-image).

**Comment by Itxaka** [comment]
moved this into elemental as elemental-cli already provides this.

Ok this is what I thougth about.

Because you can set the dirs in the manifest.yaml file we only need the proper artifacts in the TOOL IMAGE, as thats the one that its used to build the iso.
So lets have a package that ships the artifacts that we used to have from the toolkit repos: https://build.opensuse.org/package/show/home:itxaka/elemental-efi
And then on offline build or whatever you want to call it, we can either add on the fly a manifest.yaml file with those dirs so it doesnt need to go to the internet to pick anything, or we can even add flags to the build-iso file to provide those dirs on the command line as flags.


Still, having the build-iso callable from rancher manager is...weird. Like wht is the usecase there, do everything via the UI? Who does that? How would that work? Where is the iso created and stored? Where are the images pulled to? and a hunderd questions more....

As usual with elemental features, this has no use case nor its urgent nor it has a clear workflow or requirements, so IMHO this is low prio, incomplete request. Why not wait until we have a real request for something like this and then discuss if its feasible, how would it work and so on? i.e. plan the feature?

**Comment by kkaempf** [comment]
> Still, having the build-iso callable from rancher manager is...weird. Like what is the usecase there, do everything via the UI?

Yes, exactly this, do everything via the UI.

> Who does that?

Every single Rancher customer. :wink: Managing k8s clusters with a UI is why Rancher Manager exists.

> How would that work? 

You select a `machineRegistration` and have a  "download ISO" button.

> Where is the iso created and stored?

It's created by `elemental-operator` and downloaded to the user's system.

**Comment by Itxaka** [comment]
> You select a machineRegistration and have a "download ISO" button.

Then this should be moved to the operator then :D

IMO this requires a clear workflow in how it would work and the steps required. Also, this would require an UI implementation, Im not sure we know how to do so so it may involve more rancher folks on the UI side.

**Comment by davidcassany** [comment]
Some comments regarding the above discussion:

* creating ISOs from the elemental-operator is an unrelated topic, an interesting feature though, but requires a proper design as this is not alight task that can be embedded anywhere. This deserves its own epic and discussion.
* The real problem is that the bootloader artifacts from the ISO are downloaded from quay.io. We need to provide them from OBS or consume them from the base image. Few rough ideas on this topic:
  * package everything as RPMs
  * add logic in `elemental build-iso` and consume everything from the base image. This adds constraints to the base image to include requires packages and it is damn hard to be distro agnostic.
  * Explore building container images with the required content in OBS (with kiwi and some scripting it should be possible)
  * Add Luet packaging in OBS (it will be a damn huge epic including autobuild team into the picture...)

**Comment by davidcassany** [comment]
Done by rancher/elemental-cli#316 and some follow ups to adapt rancher/elemental. Opening a new card to ensure the code is also adapted in rancher/elemental-toolkit.
