### ISSUE TITLE
Switch (testing) to Teal53

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#297]
Use the artifacts from `isv:Rancher:Elemental:Teal53` (instead of `isv:Rancher:Elemental:Teal52`) in testing.

**Comment by Itxaka** [comment]
but testing on github is done using the github artifacts, i.e.:

 - latest elemental-cli from elemental-cli-ci repo
 - latest elemental-operator from elemental-operator-ci repo
 - latest rancher-system-agent from rancher-system-agent repo

Testing on github is only setup for the latest most recent versions published as it should be, that is done in order to catch issues while developing.

Artifacts generated from OBS should be tested in a different way as those can be behind what we have in the edge of development.

Not sure if we should mix obs and github. Cant we have a different way of testing artifacts generated by OBS? Makes no sense to me to mix those.

My thinking is, we develop on github, on main branches, which may not be ready to publish and have breaking changes, and those changes are tested in there -> Once tested, approved and whatnot those changes are propagated to OBS which builds the final image that will be available to customers/end users as "supported" (github stuff is not supported, its dev only). Those artifacts then should be tested before being published.

I mean we can have a daily job that tests the stuff already published on OBS but...how does that makes sense? Its already published adn its not reported anywhere. We cannot have it as part of our dev workflow as any changes done to the code wont be reflected on that job until the source in OBS is updated...by that time it has already been merged to master...

If the stuff is built on OBS, the testing should be done as part of OBS workflows, not github.

**Comment by Itxaka** [comment]
What we can do is change the base testing image which is currently `registry.suse.com/suse/sle-micro-rancher/5.2:latest` to 5.3

**Comment by kkaempf** [comment]
> Not sure if we should mix obs and github

No,I agree we shouldn't.

> What we can do is change the base testing image

That's also ok !

**Comment by kkaempf** [comment]
> If the stuff is built on OBS, the testing should be done as part of OBS workflows, not github.

openQA anyone ? 😉

**Comment by Itxaka** [comment]
Still missing https://github.com/rancher/elemental-toolkit/pull/1594, reopening

**Comment by Itxaka** [comment]
https://github.com/rancher/elemental-toolkit/pull/1594 was merged, closing. We now use packages and elemental with base 5.3
