### ISSUE TITLE
UI - Test RBAC role

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#385]
I think we need to test RBAC role in the UI.
https://github.com/rancher/elemental/issues/332

**Comment by kkaempf** [comment]
@agracey - what are the expectations for RBAC in Elemental UI ? Who should be able to do what ?

**Comment by agracey** [comment]
Admin should have full access by default and any other user would need the role we created to do anything (including list). 

Since it's relatively trivial to add roles ad hoc, I had figured we could get a few production use cases in to see how people use it. Then we could build in the common roles after we learn more.

**Comment by juadk** [comment]
I tried to create a Standard User with only "Elemental Administrator" and  I got 403 when I clicked on the OS management menu. After talking with dev, it will be fixed by https://github.com/rancher/elemental-ui/pull/26

**Comment by juadk** [comment]
https://github.com/rancher/elemental/pull/485 adds simple tests and I will provide more in a separate PR once the issue fixed by the UI team.
The idea is to run the k3s test as admin user and the RKE2 with a standard user granted with elemental-administrator role.
