### ISSUE TITLE
Remote Reset of Machine when Cluster is deleted or Machine is removed from Pool

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#526]
**Describe the solution you'd like:**
When a Cluster is deleted, the MachineInventory gets deleted as well but the node itself doesn't do any clean up and is left in a state where it needs to be re-provisioned by someone with physical access. 

Instead, what I would like to see is that when a cluster gets deleted (or a node is removed from the cluster):

- The MachineInventories don't get deleted 
  - The ownership link would be cleaned up
  - The status for applied plans gets reset and the "default plan" gets queued up again 
- The node is cleaned up using something like `elemental reset --reset-persistent --reset-oem --reboot`
- When the node comes back up, it looks like it was a clean rebuild

Open questions:
- What to do about plans that were included on first boot using the cloud-config? Can we replay those again?
- Should we provide a way to manually reset at any time?

**Comment by abonillabeeche** [comment]
I like all of this, and the ability to reset from the UI provided it would send the reset command and upon success, delete the object to be recreated.

**Comment by agracey** [comment]
> delete the object to be recreated

The issue with this is that we also have a feature on the roadmap where the ability to self-register can be turned off (meaning that a MachineInventory needs to already exist). This means that we need to patch the MachineInventory back to it's initial state as well.

**Comment by Itxaka** [comment]
> What to do about plans that were included on first boot using the cloud-config? Can we replay those again?

I think this and the agent configs/credentials are the important ones as those are obtained during registration, and that runs during the install.

This is a problem of not running this stuff on boot via yip files and only running it via the registration and the after-install hook :/

I dont think this is going to work so easily.

**Comment by kkaempf** [comment]
How does this work together with CAPI, bare metal host provisioning (like metal³), and Rancher cluster provisioning in general ? 🤔

**Comment by agracey** [comment]
This may need to be pulled up in priority if possible. Is that feasible?

**Comment by kkaempf** [comment]
> This may need to be pulled up in priority if possible. Is that feasible?

Let's discuss outside of GH :wink:

**Comment by anmazzotti** [comment]
From meeting minutes: 

1. Keep the elemental-system-agent alive by default
2. Create finalizer logic on a Cluster and/or MachineInventory deletion
3. Such logic should trigger (somehow) a machine reset

**Comment by anmazzotti** [comment]
A very drafted documentation is available here: https://github.com/anmazzotti/elemental-docs/blob/document-machine-reset-workflow/docs/reset.md

Some recap and updates on the changes required by this issue:

- `elemental-system-agent` will always run by default on active systems 
- the `MachineRegistration` definition will expose a `spec.config.resettable` toggle, to allow automatic reset to be performed on the associated machines. Default is false, this is an opt-in feature
- it will also be possible to flag `MachineInventory` as resettable, using the `elemental.cattle.io/resettable: true` annotation
- if a `MachineInventory` can be reset, then just before deletion a finalizer will create a reset plan that will be executed by the `elemental-system-agent`
- within the reset workflow, from the recovery partition, the `COS_PERSISTENT` and `COS_OEM` will be formatted. A new registration will also occur, and the `spec.config.cloud-config` definition will be applied as new. This gives a chance to the users to update the `MachineRegistration` definition and trigger a reset on a machine so that the new changes will be applied, for example to rotate the user credentials or authorized keys. Note that a new `MachineInventory` will be created so that a reset machine will appear as "new".

**Comment by kkaempf** [comment]
> 
>     * `elemental-system-agent` will always run by default on active systems

Ok to have two system-agents for the time being. But the long-term plan is to only have one running 😉 

> 
>     * within the reset workflow, from the recovery partition, the `COS_PERSISTENT` and `COS_OEM` will be formatted.

Not sure if formatting is sufficient. I'd rather `dd` with `/dev/zero` or `/dev/random`.

**Comment by davidcassany** [comment]
> Not sure if formatting is sufficient. I'd rather `dd` with `/dev/zero` or `/dev/random`.

Yes, but I'd make it an opt in feature and should be mapped to the elemental client as part of the `reset` command, probably something like `elemental reset --shred-data`. The persistent partition can be huge, so completely rewrite it can be a long process, I would not do that by default.

I think this should be part of later on improvements.

**Comment by anmazzotti** [comment]
Under the suggestion of @davidcassany, I'm going to expose some more options in the `MachineRegistry`. 
This should easily allow to add `--shred-data` and customize reset options.
Something like:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-nodes
  namespace: fleet-default
spec:
  config:
      elemental:
          reset:
             enabled: false
             reset-persistent: true
             reset-oem: true
```
