### ISSUE TITLE
MachineInventory should track the hosts IP Address

### ISSUE THREAD

**Issue by abonillabeeche** [rancher/elemental#629]
**Describe the solution you'd like:**
Trying to troubleshoot or access a node directly requires knowing the IP address of a node. This isn't collected by `elemental-register`
We should collect the IP address of the node and likely run `elemental-register` every few hours to update any changes.

**Anything else you would like to add:**
This is obviously a high-priority requirement to access edge/remote systems and manage nodes that are far from the operators.

**Comment by agracey** [comment]
It would also be good to label if the ip address is static or dhcp and how long the lease time is (can a client know the lease time?)

**Comment by fgiudici** [comment]
Yep, I think too we shouldn't provide the lease time: the client will try to renew the same IP starting when the lease time reaches half time. If the client (the registered node) is not rebooted, it will renew the lease before it expires.
If the client is rebooted, chances are it could get a different IP: I think anyway that at every boot the registered node should give a run to the register client to update labels, and so the IP address.

One more note: let's use annotations instead of labels to store IP. We don't have constraints on the values (and so we would be IPv6 ready). Moreover, we will not allow filtering on the IP, so it makes perfectly sense to have it stored in annotations.

**Comment by agracey** [comment]
My thought for the lease time is that an admin could use it to diagnose potential misconfigurations

Can you watch for annotation changes? An admin might want to automate resetting a node if/when a node's ip changes (as it will effectively be dropped from the cluster)

**Comment by kkaempf** [comment]
:+1: on annotations if they don't have the value restrictions label values have.

But not sure about the usability if every other client (hardware) parameter is available via labels 🤔

**Comment by fgiudici** [comment]
Reopening as we could easily add info from the host in the annotations now... let's start with the IP address :-)

**Comment by kkaempf** [comment]
:+1: on the title change
