### ISSUE TITLE
Support nmstate to configure networking for the host being provisioned

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental#887]
Spike card to explore how [nmstate](https://github.com/nmstate/kubernetes-nmstate) could be integrated in Elemental and check which are the supported configurations from nm-state.

**Comment by anmazzotti** [comment]
A little comment on this topic. I was wondering the same for the CAPI project, [this](https://github.com/rancher-sandbox/cluster-api-provider-elemental/issues/28) is the related issue.

My proposal is to consume the [IPAM Provider](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220125-ipam-integration.md#ipam-provider) API. Since this is an API, then it should be possible to implement providers for different IPAM solutions as we see fit.
An in-cluster reference implementation can be found [here](https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster).

This is currently part of CAPI, but my understanding is that (at least in recent Rancher versions) this should be available for the elemental-operator to consume.

**Comment by kkaempf** [comment]
For reference https://pretalx.com/devconf-cz-2024/talk/XZSYXW/

**Comment by fgiudici** [comment]
The natural introduction of Elemental Declarative Networking would involve extending https://github.com/rancher/yip to support (declarative) network configuration. The syntax could be [the cloud-config one](https://cloudinit.readthedocs.io/en/latest/reference/network-config.html) or the one from [nmstate](https://nmstate.io/), since we would anyway support only NetworkManager as the network configuration tool on the registering hosts.

In both the cases,  [nmstate](https://nmstate.io/) would be the ideal backend renderer.

At present, complex network configuration can be achieved creating NetworkManager configuration through cloud-config customization.
What is missing is providing a convenient way to assign IP addresses when DHCP is not available on the network, something that [nmstate](https://nmstate.io/) nor [cloud-config](https://cloudinit.readthedocs.io/en/latest/reference/network-config.html) provide.

For this reason, the networking enhancements in Elemental will be on IP address management (IPAM) solutions (see https://github.com/rancher/elemental/issues/1459).
