### ISSUE TITLE
ros-installer on aarch64 does not install firmware file and u-boot bootloader

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental#97]
ros-installer works nicely on aarch64, partitioning, formatting, and installing the given storage media. However on reboot, RasPi fails with "Firmware missing".

It's the content of the following RPMs that needs to be copied to the first (FAT) partition:
* raspberrypi-firmware-2022.03.01-2.1.noarch
* raspberrypi-firmware-config-2022.03.01-2.1.noarch
* raspberrypi-firmware-dt-2022.02.25-1.1.noarch
* u-boot-rpiarm64-2022.01-3.1.aarch64

**Comment by mudler** [comment]
I'm not sure where ros-installer should be actually called in this scenarios. while you dump the drive, that one should be the booting medium, so no other installation steps should be required, except providing a valid cloud-init config. Or I am missing some other cases here?

**Comment by mudler** [comment]
If you intend to register it, I think we need another specific piece here that have to be extracted from the installation in order to register the node. 

In the platform-specific images are a raw disk dump of the installation with the firmware bits, so the registration process needs to be handled off later separately - performing an installation (again) is sub-optimal and requires the installer to know about all the specific bits (that we don't want to).

**Comment by kkaempf** [comment]
I'm following the same steps as with x86_64. ros-installer is called from the boot medium (ISO for x86_64, USB stick for RasPi).

**Comment by kkaempf** [comment]
The RasPi fails to find a valid cloud-init config (not sure why), so I just run `ros-installer` from the command line, point it to the right storage medium (SD card in my case) and it happily churns away.

**Comment by mudler** [comment]
that's not a scenario currently supported by elemental. At the moment cOS-toolkit can generate specific platform images with the derivative installed that can be booted directly from the SD card

**Comment by Itxaka** [comment]
Not valid anymore, reopen when we have a way of creating device images and can test them
